# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 58db5139243e1528ad86dec76a76178cd2e5c8ebc51a85aa5c39e6b28e22453e7c35be6fb43b88244b41701b074d9a4b3ba53d45d7b6d32d52f022a0f7299003

test:
  secret_key_base: 9b6075f65f70c99608e893010ae6232878b4d21ae326943dcf970857fb796ba9482405a8bbfd52c580c48805929bd569adbba5282611bcf50809f3e176aed241

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
